#!/usr/bin/env bash
# installing nginx locally with a redirect from our localhost

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
new="\tlocation /redirect_me {\n\treturn 301 \$scheme://https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
old="\tlocation / {"
sed -i "s@^$old@$new@" /etc/nginx/sites-available/default
