#!/usr/bin/env bash
# displays 1 to 100, replacing multiples of 3 with Fizz, multiples of 5 with Buzz, and multiples of both with FizzBuzz
for n in {1..100};
do
    mod3=$((n % 3))
    mod5=$((n % 5))
    if [ $mod3 -eq 0 ] && [ $mod5 -eq 0 ];
    then
	echo "FizzBuzz"
    elif [ $mod3 -eq 0 ];
    then
	echo "Fizz"
    elif [ $mod5 -eq 0 ];
    then
	echo "Buzz"
    else
	echo "$n"
    fi
done
