#!/usr/bin/env bash
# displays the contents of file /etc/passwd with only username, user id, and home directory path
f="/etc/passwd"
while read -r line
do
    echo "$line" | cut -d: -f1,3,6
done < $f
