#!/usr/bin/env bash
# displays the content of file /etc/passwd using while loop + IFS in a sentence
f="/etc/passwd"
while read -r line
do
    u=$(echo "$line" | cut -d: -f1)
    g=$(echo "$line" | cut -d: -f4)
    h=$(echo "$line" | cut -d: -f6)
    c=$(echo "$line" | cut -d: -f7)
    ui=$(echo "$line" | cut -d: -f3)
    p=$(echo "$line" | cut -d: -f2)
    i=$(echo "$line" | cut -d: -f5)
    echo "The user $u is part of the $g gang, lives in $h and rides $c. $ui's place is protected by the passcode $p, more info about the user here: $i"
done < $f
