#!/usr/bin/env bash
# loops 1 to 10 and prints bad luck for 4, good luck for 8, and Holberton School the rest
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ];
	then
		echo "bad luck"
	elif [ $i -eq 8 ];
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((i++))
done
