#!/usr/bin/env bash
# displays 1 to 20 and "bad luck from China" for 4, "bad luck from Japan" for 9, and "bad luck from Italy" for 17
i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
	    4)
		echo "bad luck from China"
		;;
	    9)
		echo "bad luck from Japan"
		;;
	    17)
		echo "bad luck from Italy"
		;;
	esac
	((i++))
done
