#!/usr/bin/env bash
# gives information about holbertonschool file
h="holbertonschool"
if [ -e $h ];
then
	echo "holbertonschool file exists"
	if [ -s $h ];
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f $h ];
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exists"
fi
